version: '3'
services:
  php-app:
    build:
      context: ./php-app
      dockerfile: dockerfile
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
      - "9000:9000"
  payara5:
    build:
      context: ./payara5
      dockerfile: dockerfile
    ports:
      - "23:22"
      - "4848:4848"
      - "8080:8080"
      - "8181:8181"
  edbpg:
    build:
      context: ./edb_pg
      dockerfile: dockerfile
    ports:
      - "24:22"
      - "5432:5432"
      - "5444:5444"

